/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.PersonaJpaController;
import controlador.exceptions.NonexistentEntityException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import modelo.Persona;
import modelo.Usuario;
import modeloTablaPersona.ModeloTablaPersona;
import persistencia.Factory;

/**
 *
 * @author Diego Cale Pillco
 */
public class AdmininistrarPersona extends javax.swing.JFrame {

    /**
     * Creates new form AdmininistrarPersona
     */
    private final ModeloTablaPersona modeloTablapersona;
    private final Usuario usuario;
    private final PersonaJpaController pc;
    private final Factory f;
    private final TableRowSorter trsFiltro;
    private final JComponent component = new JCheckBox();
    private boolean value = false; // valor de la celda

    public AdmininistrarPersona(Usuario u, Factory f) {
        this.modeloTablapersona = new ModeloTablaPersona();
        this.usuario = u;
        this.f = f;
        this.pc = new PersonaJpaController(this.f.getEntityManagerFactory());
        initComponents();
        this.modeloTablapersona.setFilasPersonas(pc.findPersonaEntities());
        trsFiltro = new TableRowSorter(jtTablaPersona.getModel());
        jtTablaPersona.setRowSorter(trsFiltro);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelImageReflect1 = new org.edisoncor.gui.panel.PanelImageReflect();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaPersona = new javax.swing.JTable();
        bttAgregar = new javax.swing.JButton();
        bttEditar = new javax.swing.JButton();
        bttCancelar = new javax.swing.JButton();
        bttEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        txtCedulaBuscar = new org.edisoncor.gui.textField.TextFieldRoundBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(255, 204, 51));
        panelRectTranslucido1.setColorPrimario(new java.awt.Color(0, 0, 204));
        panelRectTranslucido1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panelRectTranslucido1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtTablaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtTablaPersona.setShowHorizontalLines(false);
        jtTablaPersona.setModel(modeloTablapersona);
        jScrollPane1.setViewportView(jtTablaPersona);

        panelRectTranslucido1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 970, 280));

        bttAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addUs.png"))); // NOI18N
        bttAgregar.setText("Agregar");
        bttAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregarActionPerformed(evt);
            }
        });
        panelRectTranslucido1.add(bttAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 40));

        bttEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        bttEditar.setText("Editar");
        bttEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditarActionPerformed(evt);
            }
        });
        panelRectTranslucido1.add(bttEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, 40));

        bttCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cross.gif"))); // NOI18N
        bttCancelar.setText("Cancelar");
        bttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarActionPerformed(evt);
            }
        });
        panelRectTranslucido1.add(bttCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 100, 40));

        bttEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        bttEliminar.setText("Eliminar");
        bttEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarActionPerformed(evt);
            }
        });
        panelRectTranslucido1.add(bttEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 100, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Administración de Personas");
        panelRectTranslucido1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 570, -1));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personas.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        panelRectTranslucido1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 150, 140));

        txtCedulaBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaBuscarKeyTyped(evt);
            }
        });
        panelRectTranslucido1.add(txtCedulaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bttCancelarActionPerformed

    private void bttAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregarActionPerformed
        // TODO add your handling code here:
        VentanaPersona vp = new VentanaPersona(this, true, modeloTablapersona, new Persona(), pc);
        vp.setVisible(true);
    }//GEN-LAST:event_bttAgregarActionPerformed

    private void bttEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditarActionPerformed
        if (jtTablaPersona.getSelectedRow() != -1) {
            ModeloTablaPersona model = (ModeloTablaPersona) jtTablaPersona.getModel();
            Persona personaSelected = model.getPersonaSeleccionada();
            VentanaPersona vp = new VentanaPersona(this, false, modeloTablapersona, personaSelected, pc);
            vp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor debe haber seleccionado una fila");
        }
    }//GEN-LAST:event_bttEditarActionPerformed

    private void bttEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarActionPerformed
        if (jtTablaPersona.getSelectedRow() != -1) {
            try {
                String ps = JOptionPane.showInputDialog("Confirme su contraseña para realizar esta acción");
                if (ps.equals(usuario.getContrasenia())) {
                    ModeloTablaPersona model = (ModeloTablaPersona) jtTablaPersona.getModel();
                    Persona personaSelected = model.getPersonaSeleccionada();
                    model.deleteRow(personaSelected);
                    try {
                        pc.destroy(personaSelected.getIdPersona());
                        JOptionPane.showMessageDialog(null, "Eliminación Correcta");
                    } catch (NonexistentEntityException e) {
                        System.out.println("No se puede Eliminar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
                }
            } catch (NullPointerException e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor debe haber seleccionado una fila");
        }
    }//GEN-LAST:event_bttEliminarActionPerformed

    private void txtCedulaBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaBuscarKeyTyped
         txtCedulaBuscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                filtro();
            }
        });
    }//GEN-LAST:event_txtCedulaBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgregar;
    private javax.swing.JButton bttCancelar;
    private javax.swing.JButton bttEditar;
    private javax.swing.JButton bttEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtTablaPersona;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImageReflect panelImageReflect1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtCedulaBuscar;
    // End of variables declaration//GEN-END:variables

    public void filtro() {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtCedulaBuscar.getText(), 3));
    }

}
