/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Usuario;
import persistencia.Factory;
/**
 *
 * @author Diego Cale Pillco
 */
public class AdministracionModulos extends javax.swing.JFrame {

    private final Usuario usuario;
    private Factory f = null;

    public AdministracionModulos(Usuario u, Factory f, PrincipalAcceso parent) {
        this.usuario = u;
        this.f = f;
        parent.setVisible(false);
        initComponents();
        this.setExtendedState(AdministracionModulos.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAero1 = new org.edisoncor.gui.button.ButtonAero();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttAdminPersonas = new javax.swing.JButton();
        bttAdminLista = new javax.swing.JButton();
        bttGenerarVoto = new javax.swing.JButton();
        bttReportes = new javax.swing.JButton();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        bttExit = new org.edisoncor.gui.button.ButtonIcon();

        buttonAero1.setText("buttonAero1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 60)); // NOI18N
        jLabel1.setText("Sistema de Votación Electrónica");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 850, 60));

        bttAdminPersonas.setBackground(new java.awt.Color(0, 51, 153));
        bttAdminPersonas.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        bttAdminPersonas.setForeground(new java.awt.Color(255, 255, 255));
        bttAdminPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personas.png"))); // NOI18N
        bttAdminPersonas.setText("ADMINISTRAR PERSONAS");
        bttAdminPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAdminPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(bttAdminPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 630, 270));

        bttAdminLista.setBackground(new java.awt.Color(0, 51, 153));
        bttAdminLista.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        bttAdminLista.setForeground(new java.awt.Color(255, 255, 255));
        bttAdminLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        bttAdminLista.setText("ADMINISTRAR LISTAS");
        jPanel1.add(bttAdminLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 670, 280));

        bttGenerarVoto.setBackground(new java.awt.Color(0, 51, 153));
        bttGenerarVoto.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        bttGenerarVoto.setForeground(new java.awt.Color(255, 255, 255));
        bttGenerarVoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/votocobas.png"))); // NOI18N
        bttGenerarVoto.setText("VOTO ELECTRÓNICO");
        bttGenerarVoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGenerarVotoActionPerformed(evt);
            }
        });
        jPanel1.add(bttGenerarVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 630, 280));

        bttReportes.setBackground(new java.awt.Color(0, 51, 153));
        bttReportes.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        bttReportes.setForeground(new java.awt.Color(255, 255, 255));
        bttReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        bttReportes.setText("REPORTES");
        bttReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReportesActionPerformed(evt);
            }
        });
        jPanel1.add(bttReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 670, 270));

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_elecciones2018.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 240, 100));

        bttExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        bttExit.setText("buttonIcon1");
        bttExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExitActionPerformed(evt);
            }
        });
        jPanel1.add(bttExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 110, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    AdmininistrarPersona aPersonas;
    private void bttAdminPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAdminPersonasActionPerformed
        // TODO add your handling code here:
        if (aPersonas == null) {
            aPersonas = new AdmininistrarPersona(usuario, f);
            aPersonas.setVisible(true);
        } else {
            aPersonas.setVisible(true);
        }
    }//GEN-LAST:event_bttAdminPersonasActionPerformed

    private void bttExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PrincipalAcceso().setVisible(true);
    }//GEN-LAST:event_bttExitActionPerformed
     VentanaVotoElectronico vElectronico;
    private void bttGenerarVotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGenerarVotoActionPerformed
        // TODO add your handling code here:
        if (vElectronico == null) {
            vElectronico = new  VentanaVotoElectronico(usuario, f);
        } else {
            vElectronico.setVisible(true);
        }
    }//GEN-LAST:event_bttGenerarVotoActionPerformed

     VentanaEstadistica vEstadistica = null;
    private void bttReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReportesActionPerformed
        // TODO add your handling code here:
        if (vEstadistica == null) {
            vEstadistica = new VentanaEstadistica();
            vEstadistica.setVisible(true);
        } else {
            vEstadistica.setVisible(true);
        }
    }//GEN-LAST:event_bttReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAdminLista;
    private javax.swing.JButton bttAdminPersonas;
    private org.edisoncor.gui.button.ButtonIcon bttExit;
    private javax.swing.JButton bttGenerarVoto;
    private javax.swing.JButton bttReportes;
    private org.edisoncor.gui.button.ButtonAero buttonAero1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    // End of variables declaration//GEN-END:variables
}
